version: '3.7'

services:
  backend:
    build:
      context: .
      args:
        GIT_HASH: docker-compose
    ports:
    - 8080:8080
    environment:
      HOST: 0.0.0.0
      PORT: 8080
      DATABASE_CONNECTION: sqlite:///data/sqlite.db?mode=rwc
      VECTOR_CONNECTION: hnsw:///data
    volumes:
      - ./data:./data