[package]
name = "sightglass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1.68"
bytes = "1.2.1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0.32", features = ["derive", "env"] }
dotenv = { workspace = true }
dotenv_codegen = { workspace = true }
futures = "0.3.28"
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = "0.24"
strum_macros = "0.24"
tiktoken-rs = "0.4.2"
thiserror = "1.0"
tokio = { workspace = true }
tracing = { workspace = true }
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true }
url = "2.3"
uuid = { version = "1.3.1", default-features = false, features = ["serde", "v5"] }

api = { path = "../../lib/api" }