[package]
name = "sightglass"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
async-trait = "0.1.68"
bytes = "1.2.1"
chrono = { version = "0.4", features = ["serde"] }
clap = { version = "4.0.32", features = ["derive", "env"] }
dotenv = "0.15.0"
dotenv_codegen = "0.15.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
strum = "0.24"
strum_macros = "0.24"
tiktoken-rs = "0.4.2"
thiserror = "1.0"
tokio = { version = "1.25.0", features = ["full"] }
tracing = "0.1"
tracing-log = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "std"] }
url = "2.3"
uuid = { version = "1.3.1", default-features = false, features = ["serde", "v5"] }

api = { path = "../../lib/api" }